import React, { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Save, LogOut } from "lucide-react";
import { backendUrl } from "./config";

const showToast = (message, type = "info") => {
  const bgColor =
    type === "success"
      ? "#4ade80"
      : type === "error"
      ? "#ef4444"
      : type === "warning"
      ? "#f59e0b"
      : "#3b82f6";
  const toast = document.createElement("div");
  toast.textContent = message;
  toast.style.cssText = `
    position: fixed; top: 20px; right: 20px; z-index: 9999;
    background: ${bgColor}; color: white; padding: 12px 16px;
    border-radius: 6px; font-size: 14px; max-width: 300px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.15); transition: all 0.3s ease;
  `;
  document.body.appendChild(toast);
  const displayTime =
    message.includes("import") || message.includes("Import") ? 4000 : 1000;
  setTimeout(() => {
    toast.style.opacity = "0";
    setTimeout(() => document.body.removeChild(toast), 300);
  }, displayTime);
};

const Import = () => {
  const navigate = useNavigate();
  const [currentUser, setCurrentUser] = useState(null);
  const [userLoaded, setUserLoaded] = useState(false);
  const fileInputRef = useRef(null);
  // Existing states and logic (not changed)...
  const [loading, setLoading] = useState(false);
  // New states for email redirect config
  const [allowEmailRedirect, setAllowEmailRedirect] = useState(false);
  const [redirectEmailTo, setRedirectEmailTo] = useState("");
  // Store both value and id for each config to pass id on save
  const [allowEmailRedirectId, setAllowEmailRedirectId] = useState(0);
  const [importLoading, setImportLoading] = useState(false);
  const [redirectEmailToId, setRedirectEmailToId] = useState(0);
  const [selectedFile, setSelectedFile] = useState(null);

  useEffect(() => {
    // Existing user session loading logic
    const userInfo = localStorage.getItem("currentUser");
    if (userInfo) {
      try {
        const parsedUser = JSON.parse(userInfo);
        if (!parsedUser.username) {
          parsedUser.username =
            parsedUser.id === "john"
              ? "john.doe"
              : parsedUser.id === "jane"
              ? "jane.smith"
              : parsedUser.id;
        }
        setCurrentUser(parsedUser);
        setUserLoaded(true);
      } catch (error) {
        alert("Session expired. Please login again.");
        navigate("/");
      }
    } else {
      navigate("/");
    }

    // Fetch config values from API on mount
    fetch(`${backendUrl}/api/ConfigValues`)
      .then((res) => res.json())
      .then((data) => {
        // Map the response data to the local states
        const redirectConfig = data.find(
          (item) => item.name === "ALLOW_EMAIL_REDIRECT"
        );
        const emailConfig = data.find(
          (item) => item.name === "REDIRECT_EMAIL_TO"
        );

        if (redirectConfig) {
          setAllowEmailRedirect(redirectConfig.value === "true");
          setAllowEmailRedirectId(redirectConfig.id);
        }
        if (emailConfig) {
          setRedirectEmailTo(emailConfig.value);
          setRedirectEmailToId(emailConfig.id);
        }
      })
      .catch((err) => {
        console.error("Error fetching config values:", err);
      });
  }, [navigate]);

  const handleLogout = () => {
    localStorage.removeItem("currentUser");
    setCurrentUser(null);
    setUserLoaded(false);
    // alert("Logged out successfully");
    navigate("/");
  };

  const handleSave = () => {
    setLoading(true);
    const nowISOString = new Date().toISOString();
    // Build payload with current config values.
    // id is not sent because it may be auto-generated by backend or keep as 0
    // Replace id with real id if needed by your backend.
    const payload = [
      {
        name: "ALLOW_EMAIL_REDIRECT",
        value: allowEmailRedirect.toString(),
        createdAt: nowISOString,
        id: allowEmailRedirectId || 0,
      },
      {
        name: "REDIRECT_EMAIL_TO",
        value: redirectEmailTo,
        createdAt: nowISOString,
        id: redirectEmailToId || 0,
      },
    ];

    fetch(`${backendUrl}/api/ConfigValues`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    })
      .then(() => {
        showToast("Settings saved successfully");
        setLoading(false);
      })
      .catch((err) => {
        // console.error("Save error:", err);
        showToast("Failed to save settings");
        setLoading(false);
      });
  };

  const handleImportFile = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      setSelectedFile(file);
    }
  };

  const handleImportClick = async (e) => {
    e.preventDefault();
    if (!selectedFile) {
      showToast("No file selected", "error");
      return;
    }
    if (!selectedFile.name.toLowerCase().endsWith(".csv")) {
      showToast("Please select a CSV file", "error");
      return;
    }
    const formData = new FormData();
    formData.append("file", selectedFile); // Use state here!
    try {
      setImportLoading(true);
      const importResponse = await fetch(
        `${backendUrl}/api/Timesheet/import-projects-csv?Username=${encodeURIComponent(
          currentUser?.name
        )}`,
        {
          method: "POST",
          body: formData,
        }
      );
      if (importResponse.ok) {
        showToast("Import completed successfully", "success");
        // Optionally refresh table
        setLoading(true);
        try {
          const refreshedResp = await fetch(
            `${backendUrl}/api/Timesheet/list`,
            {
              method: "GET",
              headers: { "Content-Type": "application/json" },
            }
          );
          if (refreshedResp.ok) {
            const refreshedData = await refreshedResp.json();
            setRows(refreshedData);
          }
        } finally {
          setLoading(false);
        }
      } else {
        showToast("Import failed", "error");
      }
    } catch (error) {
      showToast("Import error", "error");
      console.error(error);
    } finally {
      setImportLoading(false);
      setSelectedFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    }
  };

  if (!userLoaded || !currentUser) {
    return <div>Loading...</div>;
  }

  return (
    <div className="min-h-screen bg-[#f9fafd] flex flex-col overflow-auto">
      <div className="flex-1 flex flex-col items-center justify-start p-6">
        <div className="w-full flex flex-col items-center">
          {/* Header (existing, unchanged) */}
          <div className="w-full flex justify-between items-center mb-4 px-4 py-3 bg-gray-800 border-b border-gray-200 shadow-sm rounded-t-lg">
            <div className="w-1/3">
              <h1 className="text-xl font-semibold text-white">
                Welcome,{" "}
                <span className="font-bold text-blue-600">
                  {currentUser?.name}
                </span>
              </h1>
            </div>
            <div className="w-1/3 flex justify-center">
              <div className="bg-slate-800 rounded-md p-2 shadow-inner">
                <img src="/Columbus_Logo.png" alt="Logo" className="h-10" />
              </div>
            </div>
            <div className="w-1/3 flex justify-end">
              <button
                onClick={handleLogout}
                className="flex items-center gap-1.5 bg-red-100 text-red-700 px-4 py-2 rounded-md text-xs font-medium hover:bg-red-200 transition-colors shadow-sm"
              >
                <LogOut size={14} /> Logout
              </button>
            </div>
          </div>

          {/* Import Button: Now floated top-right in its own row */}
          <div className="w-full flex flex-col items-start gap-2 mt-4 px-2">
            <h2 className="font-semibold text-md">Import Master File</h2>
            <input
              ref={fileInputRef}
              type="file"
              className="border rounded px-1 py-1 text-gray-800"
              onChange={handleImportFile}
              accept=".csv"
              disabled={importLoading}
              //   style={{ minWidth: "220px" }}
            />
            <button
              onClick={handleImportClick}
              type="button"
              disabled={importLoading}
              className="bg-cyan-500 hover:bg-cyan-600 text-white px-1 py-1 rounded shadow font-semibold transition-colors text-md disabled:opacity-60 disabled:cursor-not-allowed"
              //   style={{ minWidth: "200px" }}
            >
              {importLoading ? "Processing..." : "Upload"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Import;
